source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'RxEasing_Example' do
  pod "RxEasing", :path => "../"
  pod 'RxCocoa', '~> 4.0'
  pod 'RxOptional', '~> 3.1'
  pod 'JBChartView', '~> 3.0'
end
